version: "2"
services:
    # web server
    nginx:
        container_name: docker-nginx
        build: ./nginx
        image: docker-nginx
        ports:
          - "80:8000"
          - "1022:22"
        volumes:
          # app
          - ./app/src:/var/www
          # nginx configs
          - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
          #- ./nginx/conf.d/:/etc/nginx/conf.d/:ro
          # certificates
      #    - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      #    - ./nginx/caserver.key/:/etc/nginx/server.key:ro
    php:
        container_name: docker-php
        build: ./php
        image: docker-php
        ports:
          - "2022:22"
          - "9000:9000"

    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_DATABASE: "test"
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "13306:3306"
    # Redis 3.2.10: https://hub.docker.com/_/redis/
    redis:
        container_name: redis
        image: redis:3.2.10
        volumes:
            - ./redis:/data
        ports:
            - "16379:6379"
