version: "2"
services:
    # web server
    nginx:
        container_name: docker-nginx
        build: ./nginx
        image: yangtaihua/ubuntu-nginx:1.12.2
        ports:
          - "80:8000"
          - "1022:22"
        volumes:
          # app
          - ./app/src:/var/www
          # nginx configs
          - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
          #- ./nginx/conf.d/:/etc/nginx/conf.d/:ro
          # certificates
      #    - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      #    - ./nginx/caserver.key/:/etc/nginx/server.key:ro
        depends_on:
          - php
        links:
          - php
    php:
        container_name: docker-php
        build: ./php
        image: yangtaihua/ubuntu-php:7.1.11
        ports:
          - "2022:22"
          - "9000:9000"
          - "9501:9501" #swoole server
          - "8081:8081" #swoole sd
          - "9091:9091" #swoole sd
        volumes:
          - ./app/src:/var/www
          - ./php/php.ini:/etc/php/php.ini:ro
          - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf:ro
          - ./php/php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf:ro
        depends_on:
          - mysql
          - redis
        links:
          - mysql
          - redis
    mysql:
        container_name: docker-mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_DATABASE: "test"
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "13306:3306"
    # Redis 3.2.10: https://hub.docker.com/_/redis/
    redis:
        container_name: docker-redis
        image: redis:3.2.10
        volumes:
            - ./redis:/data
        ports:
            - "16379:6379"
