
version: "2"
services:

    docker-nginx:
        container_name: docker-nginx
        build: ./nginx
        image: yangtaihua/nginx:1.15.9-alpine
        volumes:
            - ./sites:/var/www/html
            - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf:ro
        ports:
            - "80:80"
        depends_on:
            - docker-php
        links:
            - docker-php
    docker-php:
        container_name: docker-php
        build: ./php
        image: yangtaihua/php-fpm:7.3
        environment:
                    XDEBUG_CONFIG: remote_host=192.168.66.105 remote_port=9001
        volumes:
            - ./sites:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./php/php-fpm.d/app.conf:/usr/local/etc/php-fpm.d/app.conf
        ports:
            - "1022:22"
        depends_on:
          - docker-mysql
          - docker-redis
        links:
          - docker-mysql
          - docker-redis
    docker-redis:
        container_name: docker-redis
        build: ./redis
        image: yangtaihua/redis:5.0.3-alpine
        volumes:
            - ./redis/redis.conf:/home/redis.conf
        ports:
            - "16379:6379"

    docker-mysql:
        container_name: docker-mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_DATABASE: "automation"
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "13306:3306"

